name: tests
on:
    push:
        branches-ignore: [main]
    workflow_dispatch:

jobs:
    unit-tests:
        strategy:
            matrix:
                os: ['ubuntu-latest', 'windows-latest']
                node_version: [lts/-1, lts/*, latest]
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: npm
            - name: Configure GitHub CLI
              run: |
                  echo "${{ secrets.CI_GITHUB_PAT_FOR_TESTS || secrets.GITHUB_TOKEN }}" | gh auth login --with-token
                  gh auth status
            - run: npm install
            - run: npm run build
            - run: npx oclif manifest
            - run: npm run test
              env:
                  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_PAT_FOR_TESTS || secrets.GITHUB_TOKEN }}
