name: tests
on:
    push:
        branches-ignore: [main]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    unit-tests:
        strategy:
            matrix:
                node_version: [lts/-1, lts/*, latest]
            fail-fast: false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: npm
            - name: Configure GitHub CLI
              run: |
                  echo "${{ secrets.CI_GITHUB_PAT_FOR_TESTS || secrets.GITHUB_TOKEN }}" | gh auth login --with-token
                  gh auth status
            - run: npm install
            - run: npm run build
            - run: npx oclif manifest
            - run: npm run test
              env:
                  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_PAT_FOR_TESTS || secrets.GITHUB_TOKEN }}
